server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location /api {
        proxy_pass https://statit-backend.bluemeadow-174af2a3.eastus.azurecontainerapps.io;
        proxy_set_header Host statit-backend.bluemeadow-174af2a3.eastus.azurecontainerapps.io;
        proxy_ssl_server_name on;
    }
}
