spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/global_ranking
spring.datasource.username=ranking_admin
spring.datasource.password=supersecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
owid.height.csv-url=https://ourworldindata.org/grapher/average-height-by-year-of-birth.csv
