spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/statit_db}
spring.datasource.username=${DB_USERNAME:statit_admin}
spring.datasource.password=${DB_PASSWORD:freshpassword123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

owid.height.csv-url=https://ourworldindata.org/grapher/average-height-by-year-of-birth.csv
