spring.application.name=backend

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://statittest.postgres.database.azure.com:5432/postgres?sslmode=require
spring.datasource.username=Statitadmin
spring.datasource.password=testi123S

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

owid.height.csv-url=https://ourworldindata.org/grapher/average-height-by-year-of-birth.csv
